### ISSUE TITLE
new v playground issues

### ISSUE THREAD

**Issue by nedpals** [vlang/playground#2]
- [ ] https://github.com/vlang/v/issues/2677 - Outputs `Caught fatal signal 11`
- [ ] https://github.com/vlang/v/issues/2655 - Outputs `Time limit exceeded (wall clock)`
- [ ] https://github.com/vlang/v/issues/3033 - Outputs `Caught fatal signal 11`
- [ ] https://github.com/vlang/v/issues/3036 - Outputs `unfinished string literal`
- [ ] https://github.com/vlang/v/issues/5300 - invalid memory access

**Comment by ulises-jeremias** [comment]
@nedpals seems we can close this issue?

**Comment by i582** [comment]
+1, now it completely new playground

**Comment by Delta456** [comment]
I get this error when running code from https://github.com/vlang/v/issues/5300 in the new playground:

```v
fn foo() {}

fn main() {
    go foo()
} 
```


```
================ V panic ================
   module: builtin
 function: panic_error_number()
  message: `go main__foo()`: Resource temporarily unavailable
     file: /home/admin/v/vlib/builtin/builtin.c.v:143
   v hash: b40f182
=========================================
/tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:53: at panic_debug: Backtrace
/tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:143: by panic_error_number
/tmp/v_60000/../../../../../../box/code.v:12: by main__main
/tmp/v_60000/../../../../../../tmp/v_60000/code.2275483365638478202.tmp.c:17328: by main
Exited with error status 1
```

**Comment by i582** [comment]
> I get this error when running code from [vlang/v#5300](https://github.com/vlang/v/issues/5300) in the new playground:
> 
> ```v
> fn foo() {}
> 
> fn main() {
>     go foo()
> } 
> ```
> 
>  ```
> ================ V panic ================
>    module: builtin
>  function: panic_error_number()
>   message: `go main__foo()`: Resource temporarily unavailable
>      file: /home/admin/v/vlib/builtin/builtin.c.v:143
>    v hash: b40f182
> =========================================
> /tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:53: at panic_debug: Backtrace
> /tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:143: by panic_error_number
> /tmp/v_60000/../../../../../../box/code.v:12: by main__main
> /tmp/v_60000/../../../../../../tmp/v_60000/code.2275483365638478202.tmp.c:17328: by main
> Exited with error status 1
> ```
> 
> Also got `Caught fatal signal 11` when doing the same as [vlang/v#3033](https://github.com/vlang/v/issues/3033)
> 
> Rest issues are solved.

Yes, this is a known issue, can you create a separate issue to track it? The current issue doesn't look like a good place for this.

**Comment by walkingdevel** [comment]
@Delta456, fixed in #19

**Comment by i582** [comment]
It looks like all issues have been fixed, so I'm closing the issue.
